server:
  port: 8081
#  配置文件设置用户名和密码
# 如果报错，说明文件不是utf-8，需要在file encoding中设置
#spring:
#  security:
#    user:
#      name: user
#    password: user
#增加数据库连接的设置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_security_demo
    username: root
    password: root